/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /Users/artemlenskiy/ros/ugv_ws/src/kut_ugv/kut_ugv_msgs/msg/WorldObject.msg
 *
 */


#ifndef KUT_UGV_MSGS_MESSAGE_WORLDOBJECT_H
#define KUT_UGV_MSGS_MESSAGE_WORLDOBJECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>

namespace kut_ugv_msgs
{
template <class ContainerAllocator>
struct WorldObject_
{
  typedef WorldObject_<ContainerAllocator> Type;

  WorldObject_()
    : header()
    , id(0)
    , type(0)
    , data(0)
    , pose()  {
    }
  WorldObject_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0)
    , type(0)
    , data(0)
    , pose(_alloc)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _id_type;
  _id_type id;

   typedef uint16_t _type_type;
  _type_type type;

   typedef uint32_t _data_type;
  _data_type data;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;


    enum { OBSTACLE_UNKNOWN = 0 };
     enum { OBSTACLE_BARRICADE = 1 };
     enum { OBSTACLE_CONE = 2 };
     enum { OBSTACLE_PEDESTRIAN = 3 };
     enum { OBSTACLE_SPEEDBUMP = 4 };
     enum { OBSTACLE_VEHICLE = 5 };
     enum { LIGHT_ARROW_LEFT = 10 };
     enum { LIGHT_ARROW_RIGHT = 11 };
     enum { LIGHT_GREEN = 12 };
     enum { LIGHT_RED = 13 };
     enum { MARK_STOPLINE = 20 };
     enum { SIGN_CROSSROAD = 30 };
     enum { SIGN_PEDESTRIAN_ZONE = 31 };
     enum { SIGN_ROAD_WORKS = 32 };
     enum { SIGN_SPEED_MAXIMUM = 33 };
     enum { SIGN_SPEED_MINIMUM = 34 };
 

  typedef boost::shared_ptr< ::kut_ugv_msgs::WorldObject_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kut_ugv_msgs::WorldObject_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct WorldObject_

typedef ::kut_ugv_msgs::WorldObject_<std::allocator<void> > WorldObject;

typedef boost::shared_ptr< ::kut_ugv_msgs::WorldObject > WorldObjectPtr;
typedef boost::shared_ptr< ::kut_ugv_msgs::WorldObject const> WorldObjectConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kut_ugv_msgs::WorldObject_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kut_ugv_msgs::WorldObject_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kut_ugv_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'kut_ugv_msgs': ['/Users/artemlenskiy/ros/ugv_ws/src/kut_ugv/kut_ugv_msgs/msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kut_ugv_msgs::WorldObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kut_ugv_msgs::WorldObject_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kut_ugv_msgs::WorldObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kut_ugv_msgs::WorldObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kut_ugv_msgs::WorldObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kut_ugv_msgs::WorldObject_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kut_ugv_msgs::WorldObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9a72ebf70e9da006438bac04f66c9327";
  }

  static const char* value(const ::kut_ugv_msgs::WorldObject_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9a72ebf70e9da006ULL;
  static const uint64_t static_value2 = 0x438bac04f66c9327ULL;
};

template<class ContainerAllocator>
struct DataType< ::kut_ugv_msgs::WorldObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kut_ugv_msgs/WorldObject";
  }

  static const char* value(const ::kut_ugv_msgs::WorldObject_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kut_ugv_msgs::WorldObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Possible object types\n\
uint16 OBSTACLE_UNKNOWN = 0\n\
uint16 OBSTACLE_BARRICADE = 1\n\
uint16 OBSTACLE_CONE = 2\n\
uint16 OBSTACLE_PEDESTRIAN = 3\n\
uint16 OBSTACLE_SPEEDBUMP = 4\n\
uint16 OBSTACLE_VEHICLE = 5\n\
\n\
uint16 LIGHT_ARROW_LEFT = 10\n\
uint16 LIGHT_ARROW_RIGHT = 11\n\
uint16 LIGHT_GREEN = 12\n\
uint16 LIGHT_RED = 13\n\
\n\
uint16 MARK_STOPLINE = 20\n\
\n\
uint16 SIGN_CROSSROAD = 30\n\
uint16 SIGN_PEDESTRIAN_ZONE = 31\n\
uint16 SIGN_ROAD_WORKS = 32\n\
uint16 SIGN_SPEED_MAXIMUM = 33\n\
uint16 SIGN_SPEED_MINIMUM = 34\n\
\n\
std_msgs/Header header\n\
# Unique ID\n\
uint32 id\n\
# One of the types specified above\n\
uint16 type\n\
# Additional data, e.g. the actual speed limit\n\
uint32 data\n\
# 6D pose of the object\n\
geometry_msgs/Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const ::kut_ugv_msgs::WorldObject_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kut_ugv_msgs::WorldObject_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.type);
      stream.next(m.data);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct WorldObject_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kut_ugv_msgs::WorldObject_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kut_ugv_msgs::WorldObject_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "type: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.type);
    s << indent << "data: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.data);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUT_UGV_MSGS_MESSAGE_WORLDOBJECT_H
